app/urls.py
from django.conf.urls import url
from app import views


urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    # url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_login/$', views.UserLogin.as_view(), name='user_login'),
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),

]

django_login/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url, include
from app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include(('app.urls', 'app'), namespace='app')),#, namespace='app', name='app'
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

app/templates/app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
</head>
  <body>
<!--    <nav class="navbar navbar-default navbar-static-top">-->
<!--      <div class="container">-->
<!--        <ul class="nav navbar-nav">-->
<!--{# Django Home Link / Admin Link / Register Link#}-->
<!--          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>-->
<!--          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>-->
<!--          <li><a class="navbar-link" href="{% url 'app:register' %}">Register</a></li>-->
<!--          {# Some logic on what to display for last item#}-->
<!--          {% if user.is_authenticated %}-->

<!--            <li><a class="navbar-link" href="{% url 'app:dashboard' %}">Dashboard</a></li>-->
<!--            <li><a href="{% url 'logout' %}">Logout</a></li>-->
<!--          {% else %}-->
<!--            <li><a class="navbar-link" href="{% url 'app:user_login' %}">Login</a></li>-->
<!--          {% endif %}-->
<!--</ul>-->
<!--      </div>-->
<!--    </nav>-->


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
  <a class="navbar-brand" href="{% url 'index' %}">Logo</a>
<!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--    <span class="navbar-toggler-icon"></span>-->
<!--  </button>-->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
        <li class="nav-item ">
        <a class="nav-link" href="{% url 'app:register' %}">Register </a>
      </li>
    {# Some logic on what to display for last item#}
      {% if user.is_authenticated %}

<!--        <li><a class="navbar-link" href="{% url 'app:dashboard' %}">Dashboard</a></li>-->
<!--        <li><a href="{% url 'logout' %}">Logout</a></li>-->
<!--        -->

        <li class="nav-item ">
            <a class="nav-link" href="{% url 'index' %}">Home <!--<span class="sr-only">(current)</span>--></a>
          </li>


           <li class="nav-item">
            <a class="nav-link" href="{% url 'app:dashboard' %}">Dashboard</a>
           </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Settings
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    <a class="dropdown-item" href="{% url 'app:profile' %}">Profile</a>

                </div>
              </li>


      {% else %}
          <li class="nav-item">
               <a class="nav-link" href="{% url 'app:user_login' %}">Login</a>
           </li>
      {% endif %}





<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
    </div>
</nav>




    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

app/templates/app/dashboard.html
{% extends 'app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        {% if message %}
            {{ message }}
        {% else %}
            Users are : {{ users|length }}<br>
            {% for user in users %}
                User: {{ user }}
                User: {{ user.password }}
                User: {{ user.first_name  }}
                User: {{ user.last_name  }}
            {% endfor %}
        {% endif %}

    </div>
  </div>
{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the App !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
        {{ form.as_p }}
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

<!--        {# -->
<!--          <label for="username">Username:</label>-->
<!--          <input type="text" name="username" placeholder="Username">-->
<!--<label for="password">Password:</label>-->
<!--          <input type="password" name="password" placeholder="Password">-->
<!--    #}-->
<input type="submit" class="btn" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

app/templates/app/my_profile.html
{% extends "app/base.html" %}
{% block body_block %}
  <div class="container">

    <div class="jumbotron">
    {% if messages %}
        <h1>{{messages}}</h1>
        <a class="btn" href="{% url 'index' %}">Back to Home</a>
    {% endif %}

      {% if isUpdate %}
<!--        <h1>{{messages}}</h1>-->

      {% else %}
        <h1>Update Profile</h1>
<form enctype="multipart/form-data" name="profileForm" onsubmit="return validateForm()" method="POST">
          {% csrf_token %}
<!--          {{ user_form.as_p }}-->
          {{ profile_image_form.as_p }}

          <input type="submit" name="" value="Update">
        </form>
    {% endif %}
    </div>
  </div>

<script>

    function validateForm(){
        var form = document.forms["profileForm"]
        console.log(form, form.valid());
        return false;
    }
</script>
{% endblock %}

app/templates/app/register.html
{% extends "app/base.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}